### ISSUE TITLE
arg:[Embedding], 1 item(s), first item: [...], last item: [...]

### ISSUE THREAD

**Issue by jackusay** [ge9/ExecuteCommand-Pipe#1]
anyone success?

my code:
```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Classes\*\shell\makeTx]
"MUIVerb"="makeTx"

[HKEY_CURRENT_USER\SOFTWARE\Classes\*\shell\makeTx\command]
"DelegateExecute"="{FFA07888-75BD-471A-B325-59274E73400A}"
```

```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\{FFA07888-75BD-471A-B325-59274E73400A}]
"AppId"="{FFA07888-75BD-471A-B325-59274E73400A}"
@="C:\\Users\\peter\\Downloads\\build\\ExecuteCommand400A.exe h \"C:\\Program Files\\Git\\bin\\bash.exe\" -c \"xargs -d '\\n' -n1 -P0 notepad\""

[HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\{FFA07888-75BD-471A-B325-59274E73400A}\LocalServer32]
@="C:\\Users\\peter\\Downloads\\build\\ExecuteCommand400A.exe"
```

result:
![23-05-18-14-38-05-ExecuteCommand400A_BgcgBYenw4](https://github.com/ge9/ExecuteCommand-Pipe/assets/58719891/07d0dc37-49d8-4207-8d07-0cf338c7e705)

**Comment by ge9** [comment]
Have you done this after changing the argument? (from README.md)

> After the modification, rename "LocalServer32" to any other name and then return it back (this seems the easiest way to apply the change).

**Comment by jackusay** [comment]
I think I should put my command in `[HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\{FFA07888-75BD-471A-B325-59274E73400A}\LocalServer32]`

no
`HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\{FFA07888-75BD-471A-B325-59274E73400A}`
