### ISSUE TITLE
How to read the path of file?

### ISSUE THREAD

**Issue by jackusay** [ge9/ExecuteCommand-Pipe#2]
How to receive path of file from context menus?

`myscript.bat path1 path2 path3`

---

I run [example ](https://github.com/ge9/ExecuteCommand-Pipe#examples) from readme, it works great

> "C:\path\to\ExecuteCommand4000.exe" p "C:\Program Files\Git\bin\bash.exe" sh -c "cat > $HOME/out.txt"

---
but run my script, it doesn't work:
```
"C:\path\to\ExecuteCommand4000.exe" p "D:\b.bat"
```

b.bat:
```bat
@echo off
echo %1 
echo %2 
echo %3
echo %*

pause
```

**Comment by ge9** [comment]
ExecuteCommand-Pipe sends its argument through stdin/stdout, so you should use xargs to convert it into a string.
`C:\path\to\ExecuteCommand4000.exe p "C:\cygwin64\bin\xargs.exe" -d '\n' -- "/cygdrive/d/b.bat"`
will work basically.
However, b.bat will be terminated after files are passed through stdin/stdout (which is usual in pipe executions), so `pause` in your example won't behave as you expected. 
To use interactive commands, you can open another command window, for example with `start` command:
`C:\path\to\ExecuteCommand4000.exe h "C:\cygwin64\bin\xargs.exe" -d '\n' -- cmd /c start "" cmd /c "D:\b.bat"`
(used `h` option to hide the first command window)
Also, your example will fail with filepaths include " ". I tried to workaround this but haven't been successful yet.

**Comment by ge9** [comment]
Sorry, there is no problem for filepaths including space, as long as the batch file's path doesn't contain space.
