### ISSUE TITLE
can you please give  a example   to show selected multiple file paths in cmd and pause? 

### ISSUE THREAD

**Issue by iamqiz** [ge9/ExecuteCommand-Pipe#4]

**Comment by ge9** [comment]
cmd.exe seems to have no function to read input from stdin, so this may be difficult (especially if file paths contain special characters). Can you use powershell or Git Bash instead?

**Comment by ge9** [comment]
There are easier ways with some restriction.
For example, create the following bat file (C:\test.bat)
```
@echo off
for %%f in (%*) do (
  echo %%f
)
pause
```
and use this reg value
`C:\path\to\ExecuteCommand.exe a xxx "C:\test.bat" xxx`
This doesn't work when filename contains environment variable expression like `%PATH%`, and restricted by max command line length of cmd.exe, 8191 chars.

**Comment by ge9** [comment]
A better example:
```
C:\path\to\ExecuteCommand.exe h cmd /c chcp 65001 > nul & powershell -Command "$var1=($input | ForEach-Object { return $_ }); $var2=Out-String -InputObject $var1;$var3='\"'''+$var2.Replace('''','''''').Replace('‘‘','‘‘‘‘').Replace('’’','’’’’').Replace('‚‚','‚‚‚‚').Replace('‛‛','‛‛‛‛')+'''\"'; Start-Process -filepath powershell -ArgumentList '-command',echo,'--',$var3,';','cmd /c pause'"
```
This will work if input length < 32767.
To avoid 32767 limitation, I think you may have to write down input to temporary file or something.

**Comment by iamqiz** [comment]
@ge9 I have tried these two examples, both work well, thanks ! 
I seem to understand the "a xxx commandline", (when i read readme , i can not understand it)
in my understanding, the "xxx" here, is just a literal string , its "replacing"  is performed by exe automatically instead of by users, 
am i right ?😀

I also try this easy code below ,it also work 
```
C:\path\to\ExecuteCommand.exe a xx cmd /k "echo xx"
```
your work is great , thanks 👍

**Comment by ge9** [comment]
Yes, "xxx" can be any other string, automatically replaced with given filepaths. So we can choose desired string that doesn't conflict the commandline.
This is similar to xargs's -I option.
